spring:
  application:
    name: SemWork
  datasource:
    url: jdbc:postgresql://postgres:5432/semwork
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
logging:
  level:
    org:
      springframework:
        security: info
        web:
          socket: debug
    so:
      sonya:
        semwork: info
